#ifndef NEU_LAYER_LOCAL_CONTRAST_NORMALIZATION_HPP
#define NEU_LAYER_LOCAL_CONTRAST_NORMALIZATION_HPP
//20151224
#include <neu/layer/local_contrast_normalization/impl.hpp>
#endif //NEU_LAYER_LOCAL_CONTRAST_NORMALIZATION_HPP
